on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest 
        steps: 
        # checkout the repo 
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v2
          
        - name: Create Event Subscription
          id: azure_eventgridsubscriber
          uses: mlopstemplates/azure_eventgridsubscriber@master
          with:
            azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
            provider_type: "Microsoft.ContainerRegistry/registries/${{ secrets.REGISTRY_USERNAME }}"
            resource_group: ${{ secrets.RESOURCE_GROUP }}
            pattoken: ${{secrets.PATTOKEN}}
                  
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_USERNAME }}.azurecr.io 
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker pull houssemdocker/angular-app:latest
            docker tag houssemdocker/angular-app:latest ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/my-app5:v1
            docker push ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/my-app5:v1
